create table if not exists public.success_story_likes (
  id bigint generated by default as identity primary key,
  story_id text not null,
  user_id text not null,
  created_at timestamptz not null default now(),
  constraint success_story_likes_unique unique (story_id, user_id)
);

create index if not exists success_story_likes_story_id_idx
  on public.success_story_likes (story_id);

alter table public.success_story_likes enable row level security;

create policy "Anyone can view story likes"
  on public.success_story_likes for select
  using (true);

create policy "Authenticated users can like stories"
  on public.success_story_likes for insert to authenticated
  with check (auth.uid()::text = user_id);

create policy "Users can remove their story likes"
  on public.success_story_likes for delete to authenticated
  using (auth.uid()::text = user_id);
